package com.example.demo.Collection;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import java.time.LocalDateTime;
// Annotate the class as a Spring Data MongoDB Document

@Data
@Document
public class ApplicationSubmission {
    // Annotate a field as the document identifier

    @Id
    private String id;
    @Field("studentNumber")
    private String studentNumber;
    private String name;
    private String surname;
    private String email;
    private String yearOfStudy;
    private String transcript;
    private LocalDateTime created;
    private String studentNo;
    private String yearofStudy;

    public ApplicationSubmission(String studentNo, String name, String surname, String email, String yearofStudy, String transcript,LocalDateTime created) {
        this.studentNumber= studentNo;
        this.name = name;
        this.surname = surname;
        this.email = email;
        this.yearOfStudy = yearofStudy;
        this.transcript = transcript;
        this.created = created;
    }

    // Getter and setter methods for the fields are automatically generated by Lombok

}
