package com.example.demo.Collection;

import lombok.Data;
import lombok.Getter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.List;
// Annotate the class as a Spring Data MongoDB Document

@Data
@Document
@Getter
public class Course {
// Annotate a field as the document identifier

        @Id
        private String courseCode;
        private String courseName;
        private String courseConvener;
        private List<Tutor> tutors;
        private String TA;
        private String duration;
        private String year;
        private String creator;

    // Constructor for creating a Course object with courseCode and courseName
    public Course(String courseCode, String courseName) {
        this.courseCode = courseCode;
        this.courseName = courseName;
    }
    // Getter and setter methods for the fields are automatically generated by Lombok

}

