package com.example.demo.Collection;

import lombok.Data;
import lombok.Getter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.DayOfWeek;
import java.time.LocalTime;
import java.util.List;
// Annotate the class as a Spring Data MongoDB Document

@Data
@Document
@Getter

public class Tutorial {
    // Annotate a field as the document identifier

    @Id
    private String tutorialID;
    private String courseCode;
    private String title;
    private String dayOfWeek;
    private String time;
    private List<Tutor> tutTutors;
    private int numberOfTutors;
    private String venue;
//Tutorial Constructor to create a tutorial Object
    public Tutorial(String tutorialID, String courseCode,String title, String dayOfWeek, String time, int numberOfTutors) {
        this.tutorialID = tutorialID;
        this.courseCode = courseCode;
        this.title = title;
        this.dayOfWeek = dayOfWeek;
        this.time = time;
        this.numberOfTutors = numberOfTutors;
    }
    // Getter and setter methods for the fields are automatically generated by Lombok

}
