package com.example.demo.Collection;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
// Annotate the class as a Spring Data MongoDB Document

@Data
@Document

public class Tutor extends User {
    private String name;
    // Annotate a field as the document identifier

    @Id
    private String studentID;
    private  String phone;
// Getter and setter methods for the fields are automatically generated by Lombok


}
