package com.example.demo.Collection;

import lombok.Data;
import org.springframework.data.annotation.Id;
// Annotate the class as a Spring Data MongoDB Document

@Data

public class User {


    private String email;
    private  String role;
    private String password;
    // Getter and setter methods for the fields are automatically generated by Lombok


}
